spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://3.111.235.72:8888"
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - 'https://one-more-rep-frontend.vercel.app/'
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
      routes:

        - id: auth-service
          uri: http://3.111.235.72:8080
          predicates:
            - Path=/api/v1/auth/**
        - id: authority-service-user
          uri: http://65.1.243.55:8081
          predicates:
            - Path=/api/v1/user/**
          filters:
            - AuthenticationFilter
        - id: authority-service-trainer
          uri: http://65.1.243.55:8081
          predicates:
            - Path=/api/v1/trainer/**
          filters:
            - AuthenticationFilter
        - id: authority-service-tracking
          uri: http://65.1.243.55:8081
          predicates:
            - Path=/api/v1/tracking/**
          filters:
            - AuthenticationFilter
        - id: plan-service
          uri: http://65.1.243.55:8082
          predicates:
            - Path=/api/v1/plans/**
          filters:
            - AuthenticationFilter
        - id: communication-service
          uri:  http://65.1.243.55:8083
          predicates:
            - Path=/api/v1/chats/**


server:
  port: 8765

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://3.111.235.72:8761/eureka

management:
  tracing:
    sampling:
      probability: 1.0

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
